// Mocks generated by Mockito 5.4.6 from annotations
// in popcorn/test/unit_test/presentation/movie_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:popcorn/data/storage/favorite_storage.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoriteStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteStorage extends _i1.Mock implements _i2.FavoriteStorage {
  @override
  _i3.Future<bool> addToFavorite(num? id) =>
      (super.noSuchMethod(
            Invocation.method(#addToFavorite, [id]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> getFavorite() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorite, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> removeFromFavorite(num? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFavorite, [id]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
