// Mocks generated by Mockito 5.4.6 from annotations
// in pop_corn/test/golden_test/movie_detail_snapsphot_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:pop_corn/domain/model/movie_detail.dart' as _i5;
import 'package:pop_corn/domain/use_case/movie/movie_detail_use_case.dart'
    as _i2;
import 'package:pop_corn/domain/use_case/movie/movie_favorite_use_case.dart'
    as _i7;
import 'package:pop_corn/util/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MovieDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailUseCase extends _i1.Mock
    implements _i2.MovieDetailUseCase {
  MockMovieDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.MovieDetail>> getMovieDetailById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetailById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.MovieDetail>>.value(
              _i6.dummyValue<_i4.Result<_i5.MovieDetail>>(
                this,
                Invocation.method(#getMovieDetailById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.MovieDetail>>);
}

/// A class which mocks [MovieFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieFavoriteUseCase extends _i1.Mock
    implements _i7.MovieFavoriteUseCase {
  MockMovieFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addToFavorite(num? id) => super.noSuchMethod(
    Invocation.method(#addToFavorite, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFromFavorite(num? id) => super.noSuchMethod(
    Invocation.method(#removeFromFavorite, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> getFavoriteStatus(num? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteStatus, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
