// Mocks generated by Mockito 5.4.6 from annotations
// in popcorn/test/golden_test/movie_list_snapshot_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:popcorn/domain/model/movie_page_data.dart' as _i5;
import 'package:popcorn/domain/use_case/movie/movie_favorite_use_case.dart'
    as _i7;
import 'package:popcorn/domain/use_case/movie/movie_list_use_case.dart' as _i2;
import 'package:popcorn/domain/use_case/movie/search_movie_list_use_case.dart'
    as _i8;
import 'package:popcorn/util/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MovieListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListUseCase extends _i1.Mock implements _i2.MovieListUseCase {
  MockMovieListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.MoviePageData>> getMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getMovies, []),
            returnValue: _i3.Future<_i4.Result<_i5.MoviePageData>>.value(
              _i6.dummyValue<_i4.Result<_i5.MoviePageData>>(
                this,
                Invocation.method(#getMovies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.MoviePageData>>);

  @override
  _i3.Future<_i4.Result<_i5.MoviePageData>> loadMoreMovies() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreMovies, []),
            returnValue: _i3.Future<_i4.Result<_i5.MoviePageData>>.value(
              _i6.dummyValue<_i4.Result<_i5.MoviePageData>>(
                this,
                Invocation.method(#loadMoreMovies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.MoviePageData>>);
}

/// A class which mocks [MovieFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieFavoriteUseCase extends _i1.Mock
    implements _i7.MovieFavoriteUseCase {
  MockMovieFavoriteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addToFavorite(num? id) => super.noSuchMethod(
    Invocation.method(#addToFavorite, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFromFavorite(num? id) => super.noSuchMethod(
    Invocation.method(#removeFromFavorite, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> getFavoriteStatus(num? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteStatus, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [SearchMovieListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovieListUseCase extends _i1.Mock
    implements _i8.SearchMovieListUseCase {
  MockSearchMovieListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.MoviePageData>> getMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getMovies, [query]),
            returnValue: _i3.Future<_i4.Result<_i5.MoviePageData>>.value(
              _i6.dummyValue<_i4.Result<_i5.MoviePageData>>(
                this,
                Invocation.method(#getMovies, [query]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.MoviePageData>>);

  @override
  _i3.Future<_i4.Result<_i5.MoviePageData>> loadMoreMovies() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreMovies, []),
            returnValue: _i3.Future<_i4.Result<_i5.MoviePageData>>.value(
              _i6.dummyValue<_i4.Result<_i5.MoviePageData>>(
                this,
                Invocation.method(#loadMoreMovies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.MoviePageData>>);
}
